pub mod ambient_generic;
pub mod delayed_use;
pub mod env_debris;
pub mod env_explosion;
pub mod env_glow;
pub mod env_sound;
pub mod env_spark;
pub mod func_button;
pub mod func_door;
pub mod func_friction;
pub mod func_illusionary;
pub mod func_ladder;
pub mod func_rot_button;
pub mod func_wall;
pub mod info_landmark;
pub mod info_node;
pub mod info_player_deathmatch;
pub mod info_player_start;
pub mod info_target;
pub mod infodecal;
pub mod item;
pub mod light;
pub mod multi_manager;
pub mod multisource;
pub mod player;
pub mod point_entity;
pub mod spark_shower;
pub mod speaker;
pub mod stub;
pub mod target_cdaudio;
pub mod trigger_auto;
pub mod trigger_autosave;
pub mod trigger_cdaudio;
pub mod trigger_changelevel;
pub mod trigger_endsection;
pub mod trigger_hurt;
pub mod trigger_multiple;
pub mod trigger_once;
pub mod trigger_push;
pub mod trigger_relay;
pub mod trigger_teleport;
pub mod trigger_transition;
pub mod world;
pub mod world_items;

mod triggers;

use crate::export::export_entity_stub;

export_entity_stub!(aiscripted_sequence);
export_entity_stub!(beam);
export_entity_stub!(button_target);
export_entity_stub!(env_beam);
export_entity_stub!(env_blood);
export_entity_stub!(env_bubbles);
export_entity_stub!(env_fade);
export_entity_stub!(env_global);
export_entity_stub!(env_laser);
export_entity_stub!(env_lightning);
export_entity_stub!(env_render);
export_entity_stub!(env_shake);
export_entity_stub!(env_shooter);
export_entity_stub!(env_sprite);
export_entity_stub!(fireanddie);
export_entity_stub!(func_breakable);
export_entity_stub!(func_guntarget);
export_entity_stub!(func_plat);
export_entity_stub!(func_platrot);
export_entity_stub!(func_pushable);
export_entity_stub!(func_rotating);
export_entity_stub!(func_trackautochange);
export_entity_stub!(func_trackchange);
export_entity_stub!(func_tracktrain);
export_entity_stub!(func_train);
export_entity_stub!(func_traincontrols);
export_entity_stub!(gibshooter);
export_entity_stub!(item_antidote);
export_entity_stub!(item_longjump);
export_entity_stub!(item_security);
export_entity_stub!(momentary_rot_button);
export_entity_stub!(monster_furniture);
export_entity_stub!(scripted_sentence);
export_entity_stub!(scripted_sequence);
export_entity_stub!(test_effect);
export_entity_stub!(trigger);
export_entity_stub!(trigger_camera);
export_entity_stub!(trigger_changetarget);
export_entity_stub!(trigger_counter);
export_entity_stub!(trigger_gravity);
export_entity_stub!(trigger_monsterjump);
