pub use shared::consts::*;

pub mod keys {
    macro_rules! keys {
        ($($name:ident = $value:expr),* $(,)?) => {
            $(pub const $name: u8 = $value as u8;)*
        };
    }

    keys! {
        K_TAB = super::K_TAB,
        K_ENTER = super::K_ENTER,
        K_ESCAPE = super::K_ESCAPE,
        K_SPACE = super::K_SPACE,
        K_SCROLLOCK = super::K_SCROLLOCK,
        K_BACKSPACE = super::K_BACKSPACE,
        K_UPARROW = super::K_UPARROW,
        K_DOWNARROW = super::K_DOWNARROW,
        K_LEFTARROW = super::K_LEFTARROW,
        K_RIGHTARROW = super::K_RIGHTARROW,
        K_ALT = super::K_ALT,
        K_CTRL = super::K_CTRL,
        K_SHIFT = super::K_SHIFT,
        K_F1 = super::K_F1,
        K_F2 = super::K_F2,
        K_F3 = super::K_F3,
        K_F4 = super::K_F4,
        K_F5 = super::K_F5,
        K_F6 = super::K_F6,
        K_F7 = super::K_F7,
        K_F8 = super::K_F8,
        K_F9 = super::K_F9,
        K_F10 = super::K_F10,
        K_F11 = super::K_F11,
        K_F12 = super::K_F12,
        K_INS = super::K_INS,
        K_DEL = super::K_DEL,
        K_PGDN = super::K_PGDN,
        K_PGUP = super::K_PGUP,
        K_HOME = super::K_HOME,
        K_END = super::K_END,
        K_CAPSLOCK = super::K_CAPSLOCK,
        K_WIN = super::K_WIN,
        K_PAUSE = super::K_PAUSE,
        K_MWHEELDOWN = super::K_MWHEELDOWN,
        K_MWHEELUP = super::K_MWHEELUP,
        K_MOUSE1 = super::K_MOUSE1,
        K_MOUSE2 = super::K_MOUSE2,
        K_MOUSE3 = super::K_MOUSE3,
        K_MOUSE4 = super::K_MOUSE4,
        K_MOUSE5 = super::K_MOUSE5,

        K_0 = b'0',
        K_1 = b'1',
        K_2 = b'2',
        K_3 = b'3',
        K_4 = b'4',
        K_5 = b'5',
        K_6 = b'6',
        K_7 = b'7',
        K_8 = b'8',
        K_9 = b'9',

        K_A = b'a',
        K_B = b'b',
        K_C = b'c',
        K_D = b'd',
        K_E = b'e',
        K_F = b'f',
        K_G = b'g',
        K_H = b'h',
        K_I = b'i',
        K_J = b'j',
        K_K = b'k',
        K_L = b'l',
        K_M = b'm',
        K_N = b'n',
        K_O = b'o',
        K_P = b'p',
        K_Q = b'q',
        K_R = b'r',
        K_S = b's',
        K_T = b't',
        K_U = b'u',
        K_V = b'v',
        K_W = b'w',
        K_X = b'x',
        K_Y = b'y',
        K_Z = b'z',
    }
}
