pub use xash3d_shared::consts::*;

pub mod keys {
    use xash3d_shared::ffi::keys;

    macro_rules! keys {
        ($($name:ident = $value:expr),* $(,)?) => {
            $(pub const $name: u8 = $value as u8;)*
        };
    }

    keys! {
        K_TAB = keys::K_TAB,
        K_ENTER = keys::K_ENTER,
        K_ESCAPE = keys::K_ESCAPE,
        K_SPACE = keys::K_SPACE,
        K_SCROLLLOCK = keys::K_SCROLLLOCK,
        K_BACKSPACE = keys::K_BACKSPACE,
        K_UPARROW = keys::K_UPARROW,
        K_DOWNARROW = keys::K_DOWNARROW,
        K_LEFTARROW = keys::K_LEFTARROW,
        K_RIGHTARROW = keys::K_RIGHTARROW,
        K_ALT = keys::K_ALT,
        K_CTRL = keys::K_CTRL,
        K_SHIFT = keys::K_SHIFT,
        K_F1 = keys::K_F1,
        K_F2 = keys::K_F2,
        K_F3 = keys::K_F3,
        K_F4 = keys::K_F4,
        K_F5 = keys::K_F5,
        K_F6 = keys::K_F6,
        K_F7 = keys::K_F7,
        K_F8 = keys::K_F8,
        K_F9 = keys::K_F9,
        K_F10 = keys::K_F10,
        K_F11 = keys::K_F11,
        K_F12 = keys::K_F12,
        K_INS = keys::K_INS,
        K_DEL = keys::K_DEL,
        K_PGDN = keys::K_PGDN,
        K_PGUP = keys::K_PGUP,
        K_HOME = keys::K_HOME,
        K_END = keys::K_END,
        K_CAPSLOCK = keys::K_CAPSLOCK,
        K_WIN = keys::K_WIN,
        K_PAUSE = keys::K_PAUSE,
        K_MWHEELDOWN = keys::K_MWHEELDOWN,
        K_MWHEELUP = keys::K_MWHEELUP,
        K_MOUSE1 = keys::K_MOUSE1,
        K_MOUSE2 = keys::K_MOUSE2,
        K_MOUSE3 = keys::K_MOUSE3,
        K_MOUSE4 = keys::K_MOUSE4,
        K_MOUSE5 = keys::K_MOUSE5,

        K_0 = b'0',
        K_1 = b'1',
        K_2 = b'2',
        K_3 = b'3',
        K_4 = b'4',
        K_5 = b'5',
        K_6 = b'6',
        K_7 = b'7',
        K_8 = b'8',
        K_9 = b'9',

        K_A = b'a',
        K_B = b'b',
        K_C = b'c',
        K_D = b'd',
        K_E = b'e',
        K_F = b'f',
        K_G = b'g',
        K_H = b'h',
        K_I = b'i',
        K_J = b'j',
        K_K = b'k',
        K_L = b'l',
        K_M = b'm',
        K_N = b'n',
        K_O = b'o',
        K_P = b'p',
        K_Q = b'q',
        K_R = b'r',
        K_S = b's',
        K_T = b't',
        K_U = b'u',
        K_V = b'v',
        K_W = b'w',
        K_X = b'x',
        K_Y = b'y',
        K_Z = b'z',
    }
}
