pub mod keys {
    use shared::consts;

    macro_rules! keys {
        ($($name:ident = $value:expr),* $(,)?) => {
            $(pub const $name: u8 = $value as u8;)*
        };
    }

    keys! {
        K_TAB = consts::K_TAB,
        K_ENTER = consts::K_ENTER,
        K_ESCAPE = consts::K_ESCAPE,
        K_SPACE = consts::K_SPACE,
        K_SCROLLOCK = consts::K_SCROLLOCK,
        K_BACKSPACE = consts::K_BACKSPACE,
        K_UPARROW = consts::K_UPARROW,
        K_DOWNARROW = consts::K_DOWNARROW,
        K_LEFTARROW = consts::K_LEFTARROW,
        K_RIGHTARROW = consts::K_RIGHTARROW,
        K_ALT = consts::K_ALT,
        K_CTRL = consts::K_CTRL,
        K_SHIFT = consts::K_SHIFT,
        K_F1 = consts::K_F1,
        K_F2 = consts::K_F2,
        K_F3 = consts::K_F3,
        K_F4 = consts::K_F4,
        K_F5 = consts::K_F5,
        K_F6 = consts::K_F6,
        K_F7 = consts::K_F7,
        K_F8 = consts::K_F8,
        K_F9 = consts::K_F9,
        K_F10 = consts::K_F10,
        K_F11 = consts::K_F11,
        K_F12 = consts::K_F12,
        K_INS = consts::K_INS,
        K_DEL = consts::K_DEL,
        K_PGDN = consts::K_PGDN,
        K_PGUP = consts::K_PGUP,
        K_HOME = consts::K_HOME,
        K_END = consts::K_END,
        K_CAPSLOCK = consts::K_CAPSLOCK,
        K_WIN = consts::K_WIN,
        K_PAUSE = consts::K_PAUSE,
        K_MWHEELDOWN = consts::K_MWHEELDOWN,
        K_MWHEELUP = consts::K_MWHEELUP,
        K_MOUSE1 = consts::K_MOUSE1,
        K_MOUSE2 = consts::K_MOUSE2,
        K_MOUSE3 = consts::K_MOUSE3,
        K_MOUSE4 = consts::K_MOUSE4,
        K_MOUSE5 = consts::K_MOUSE5,

        K_0 = b'0',
        K_1 = b'1',
        K_2 = b'2',
        K_3 = b'3',
        K_4 = b'4',
        K_5 = b'5',
        K_6 = b'6',
        K_7 = b'7',
        K_8 = b'8',
        K_9 = b'9',

        K_A = b'a',
        K_B = b'b',
        K_C = b'c',
        K_D = b'd',
        K_E = b'e',
        K_F = b'f',
        K_G = b'g',
        K_H = b'h',
        K_I = b'i',
        K_J = b'j',
        K_K = b'k',
        K_L = b'l',
        K_M = b'm',
        K_N = b'n',
        K_O = b'o',
        K_P = b'p',
        K_Q = b'q',
        K_R = b'r',
        K_S = b's',
        K_T = b't',
        K_U = b'u',
        K_V = b'v',
        K_W = b'w',
        K_X = b'x',
        K_Y = b'y',
        K_Z = b'z',
    }
}
